name: Enforce PRs only from dev branch

on:
  pull_request:
    branches:
      - 2.x

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from dev branch
        run: |
          echo "Source branch is ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "2.x-dev" ]]; then
            echo "❌ Pull requests to '2.x' must come from '2.x-dev' only."
            exit 1
          fi